<?php

namespace ContainerH9EPHPZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEvenementControllerinscriptionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ImnksS7.App\Controller\EvenementController::inscription()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ImnksS7.App\\Controller\\EvenementController::inscription()'] = ($container->privates['.service_locator.ImnksS7'] ?? $container->load('get_ServiceLocator_ImnksS7Service'))->withContext('App\\Controller\\EvenementController::inscription()', $container);
    }
}
