<?php

namespace ContainerH9EPHPZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurityControllerlogoutService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.l6hZplE.App\Controller\SecurityController::logout()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.l6hZplE.App\\Controller\\SecurityController::logout()'] = ($container->privates['.service_locator.l6hZplE'] ?? $container->load('get_ServiceLocator_L6hZplEService'))->withContext('App\\Controller\\SecurityController::logout()', $container);
    }
}
