<?php

namespace ContainerYKHSzt1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ImnksS7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ImnksS7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ImnksS7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'evenement' => ['privates', '.errored..service_locator.ImnksS7.App\\Entity\\Evenement', NULL, 'Cannot autowire service ".service_locator.ImnksS7": it needs an instance of "App\\Entity\\Evenement" but this type has been excluded in "config/services.yaml".'],
            'evenementRepository' => ['privates', 'App\\Repository\\EvenementRepository', 'getEvenementRepositoryService', true],
        ], [
            'entityManager' => '?',
            'evenement' => 'App\\Entity\\Evenement',
            'evenementRepository' => 'App\\Repository\\EvenementRepository',
        ]);
    }
}
