<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH9EPHPZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH9EPHPZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH9EPHPZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH9EPHPZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerH9EPHPZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'H9EPHPZ',
    'container.build_id' => '70b3f88e',
    'container.build_time' => 1718515872,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH9EPHPZ');
